CREATE TABLE tx_ppldeeplv3batchtranslation_job (
  uid int(11) unsigned NOT NULL auto_increment,
  pid int(11) DEFAULT '0' NOT NULL,
  crdate int(11) unsigned DEFAULT '0' NOT NULL,
  tstamp int(11) unsigned DEFAULT '0' NOT NULL,
  deleted tinyint(4) unsigned DEFAULT '0' NOT NULL,
  hidden tinyint(4) unsigned DEFAULT '0' NOT NULL,
  site_identifier varchar(190) DEFAULT '' NOT NULL,
  source_language_id int(11) DEFAULT '0' NOT NULL,
  target_language_id int(11) DEFAULT '0' NOT NULL,
  translation_mode varchar(80) DEFAULT '' NOT NULL,
  status varchar(40) DEFAULT '' NOT NULL,
  selected_scope_json mediumtext,
  options_json mediumtext,
  total_items int(11) DEFAULT '0' NOT NULL,
  processed_items int(11) DEFAULT '0' NOT NULL,
  blocked_items int(11) DEFAULT '0' NOT NULL,
  skipped_items int(11) DEFAULT '0' NOT NULL,
  failed_items int(11) DEFAULT '0' NOT NULL,
  translated_items int(11) DEFAULT '0' NOT NULL,
  created_by int(11) DEFAULT '0' NOT NULL,
  started_at int(11) DEFAULT '0' NOT NULL,
  lease_token varchar(40) DEFAULT '' NOT NULL,
  lease_renewed_at int(11) DEFAULT '0' NOT NULL,
  finished_at int(11) DEFAULT '0' NOT NULL,
  PRIMARY KEY (uid),
  KEY status (status),
  KEY target_language (target_language_id),
  KEY created_by (created_by)
);

CREATE TABLE tx_ppldeeplv3batchtranslation_job_item (
  uid int(11) unsigned NOT NULL auto_increment,
  pid int(11) DEFAULT '0' NOT NULL,
  crdate int(11) unsigned DEFAULT '0' NOT NULL,
  tstamp int(11) unsigned DEFAULT '0' NOT NULL,
  deleted tinyint(4) unsigned DEFAULT '0' NOT NULL,
  job_uid int(11) DEFAULT '0' NOT NULL,
  item_type varchar(40) DEFAULT '' NOT NULL,
  source_table varchar(80) DEFAULT '' NOT NULL,
  source_uid int(11) DEFAULT '0' NOT NULL,
  base_uid int(11) DEFAULT '0' NOT NULL,
  target_uid int(11) DEFAULT '0' NOT NULL,
  source_page_uid int(11) DEFAULT '0' NOT NULL,
  status varchar(40) DEFAULT '' NOT NULL,
  error_code varchar(80) DEFAULT '' NOT NULL,
  error_message text,
  source_hash varchar(64) DEFAULT '' NOT NULL,
  options_json mediumtext,
  processed_at int(11) DEFAULT '0' NOT NULL,
  PRIMARY KEY (uid),
  KEY job_uid (job_uid),
  KEY base_record (source_table,base_uid),
  KEY source_record (source_table,source_uid),
  KEY status (status)
);
